### ISSUE TITLE
`Cannot find module 'events'` after 1.1.74 upgrade

### ISSUE THREAD

**Issue by anion155** [wessberg/rollup-plugin-ts#46]
Imports of `events` module not working with `pnpm` after upgrade to v1.1.74 (does work in `npm` environment).

See example repo [here](https://github.com/anion155/rollup-plugin-ts-missing-events-bug).

**Comment by anion155** [comment]
The main difference is that dependencies have access only to packages that listed in it's deps, peerDeps, etc list. So in provided repo's `node_modules` looks like this:
```
$ ls -l node_modules
итого 12
lrwxrwxrwx 1 anion anion   57 ноя 15 02:41 events -> .pnpm/registry.npmjs.org/events/3.0.0/node_modules/events
lrwxrwxrwx 1 anion anion   58 ноя 15 02:41 rollup -> .pnpm/registry.npmjs.org/rollup/1.27.0/node_modules/rollup
drwxrwxr-x 2 anion anion 4096 ноя 15 02:41 @types
lrwxrwxrwx 1 anion anion   65 ноя 15 02:41 typescript -> .pnpm/registry.npmjs.org/typescript/3.7.2/node_modules/typescript
drwxrwxr-x 2 anion anion 4096 ноя 15 02:41 @wessberg
```

And the output of `rollup` is:
```
$ rollup --config
./index.ts → ./result.js...
[!] (plugin Typescript) TS2307: Cannot find module 'events'.
index.ts (1:30)
1 import { EventEmitter } from 'events';
                               ~~~~~~~~
```

The problem could be, that resolve mechanism was changed in version 1.1.74.

**Comment by wessberg** [comment]
This has been solved. The problem was primarily that `events` also happens to be the name of a builtin module and the resolve algorithm would short-circuit if the given module name was identical to one of Node's builtin modules since it determined it to be unresolvable. The fix has been released with [v1.1.80](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.80)
